# Generated by Django 5.0.1 on 2024-01-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_alter_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='matn',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
