# Generated by Django 5.0.1 on 2024-01-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_portfolio_matn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('mavzu', models.CharField(max_length=50)),
                ('matn', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
