# Generated by Django 5.0.1 on 2024-01-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0006_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('malumot', models.TextField()),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
