# Generated by Django 5.0.1 on 2024-01-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_subcribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcribe',
            name='malumot',
        ),
        migrations.RemoveField(
            model_name='subcribe',
            name='nomi',
        ),
    ]
